### ISSUE TITLE
jmeter kg.apc plugins are not compatible

### ISSUE THREAD

**Issue by gnupinguin** [qualersoft/jmeter-gradle-plugin#172]
**Describe the bug**
It looks like jmeterPlugin dependency resolver is not compatible with kg.apc plugins. The below exception happens:
```
Execution failed for task ':setupJMeter'.
> Could not resolve all dependencies for configuration ':jmeterPlugin'.
   > Could not find org.apache.jmeter:bom:5.5.
     Required by:
         project : > org.apache.jmeter:ApacheJMeter_core:5.5
         project : > kg.apc:jmeter-plugins-cmn-jmeter:0.7 > org.apache.jmeter:jorphan:5.5
         project : > org.apache.jmeter:ApacheJMeter_core:5.5 > org.apache.jmeter:ApacheJMeter:5.5
```

**To Reproduce**
Apply the below config to your application and perform jmRun task:

```
plugins {
    id("de.qualersoft.jmeter") version "2.4.0"
}

dependencies {
    jmeterPlugin("kg.apc:jmeter-plugins-tst:2.5")
    jmeterPlugin("kg.apc:jmeter-plugins-cmn-jmeter:0.7")
    jmeterPlugin("kg.apc:jmeter-plugins-synthesis:2.2")
    jmeterPlugin("kg.apc:jmeter-plugins-filterresults:2.2")
    jmeterPlugin("kg.apc:jmeter-plugins-graphs-basic:2.0")
}

jmeter {
    tool {
        version = "5.5"
    }
}

tasks {
    register<JMeterRunTask>("jmRun") {
        jmxFile.set("Test.jmx")
    }
}
```

**Expected behavior**
Plugins should be applied correctly

**Comment by mathze** [comment]
Hi @gnupinguin,

this issue is not that the jmeter-gradle-plugin is incompatible with the kg.apc pugins. The issue is that many jmeter-libraries/plugins depends on 'org.apache.jmeter:bom:<JMeter-Version>', which unfortunately isn't available in any maven-repository I know.

To workaround this, I've added a convinient-method called 'applyBomWorkaround' which is available through `jmeter.tool`. So you can modify your jmeterPlugin-dependencies as follow:
```
jmeterPlugin("kg.apc:jmeter-plugins-tst:2.5") {
  jmeter.tool.applyBomWorkaround(this)
}
```

I thought, I mentioned this in the docu, but now I recognized, that I forgot about that.
Will fix it asap.

Thank you for pointing me to it^^

**Comment by mathze** [comment]
I've updated the docu in #173.
I would be very happy if you could take a look at it.

**Comment by gnupinguin** [comment]
@mathze Thank you, it works!
